#!/usr/bin/env bash

if ! kubectl get secret project-registry-key >/dev/null 2>&1
then
  if [ -f "$PROJECT_ROOT_PATH/private/project-registry-service-account.json" ]
  then
    local EMAIL=$(python -c"import json; print (json.load(open("'"'"$PROJECT_ROOT_PATH/private/project-registry-service-account.json"'"'"))['client_email'])")
    kubectl create secret docker-registry project-registry-key \
      --docker-username "_json_key" \
      --docker-password "$(cat "$PROJECT_ROOT_PATH/private/project-registry-service-account.json")" \
      --docker-email "$EMAIL" \
      --docker-server "https://$DOCKER_REPO"
  else
    echo "private/project-registry-service-account.json not found" 1>&2
    exit 1
  fi
fi

