#!/usr/bin/env bash

set -eo pipefail

if ! kubectl get secret project-registry-key >/dev/null 2>&1
then
  if [ -f "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME/project-registry-service-account.json.gpg" ]
  then
    EMAIL=$(kproject secrets show project-registry-service-account.json | jq --raw-output .client_email)
    kubectl create secret docker-registry project-registry-key \
      --docker-username "_json_key" \
      --docker-password "$(kproject secrets show project-registry-service-account.json)" \
      --docker-email "$EMAIL" \
      --docker-server "https://$DOCKER_REPO"
    kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "project-registry-key"}]}'
  else
    echo "private/$ENVIRONMENT_NAME/project-registry-service-account.json.gpg not found" 1>&2
    exit 1
  fi
fi

