#!/usr/bin/env bash

set -o pipefail

if [ -z "$1" ]
then
  if [ "$(kubectl get secret | wc -l)" -lt 2 ]
  then
    kproject secrets deploy --all
  else
    kproject secrets deploy
  fi
  kproject secrets create-registry-key
  (
    config_get_minikube
    export MINIKUBE
    helm upgrade --install $HELM_RELEASE_NAME \
      -f <("$PROJECT_ROOT_PATH/environments/$ENVIRONMENT_NAME/values.yaml.sh") \
      "$PROJECT_ROOT_PATH/environments/$ENVIRONMENT_NAME/$PROJECT_ID-$ENVIRONMENT_NAME"
  )
else
  helm upgrade --install $HELM_RELEASE_NAME "$PROJECT_ROOT_PATH/services/$1"
fi


