#!/usr/bin/env bash

set -eo pipefail

(
  find "$PROJECT_ROOT_PATH/services" -type f -executable -name 'generate.sh' | bash
)

 set +e

if [ -z "$1" ]
then
  if [ "$(kubectl get secret | wc -l)" -lt "3" ]
  then
    kproject secrets deploy --all
  else
    kproject secrets deploy
  fi
  kproject secrets create-registry-key
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate apply "${ENVIRONMENT_NAME}-cluster.yaml"
  )
else
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate apply "${ENVIRONMENT_NAME}-cluster.yaml" --include=$1
  )
fi

kubectl get pods

