#!/usr/bin/env bash

CHARTS="$@"
for CHART in $CHARTS
do
  CHART=$(kproject chart path "$CHART")

  if [ ! -d "$CHART" ]
  then
    echo "$CHART not found" >&2
    exit 1
  fi

  helm upgrade --install $HELM_RELEASE_NAME "$CHART"
done

