#!/usr/bin/env bash

set -eo pipefail

(
  find "$PROJECT_ROOT_PATH/services" -type f -executable -name 'generate.sh' | bash
)

set +e

if [ -z "$1" ]
then
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate template "${ENVIRONMENT_NAME}-cluster.yaml"
  )
else
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate template "${ENVIRONMENT_NAME}-cluster.yaml" --include=$1
  )
fi


