#!/usr/bin/env bash

set -o pipefail

if [ -z "$1" ]
then
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate template "${ENVIRONMENT_NAME}-cluster.yaml"
  )
else
  (
    command cd "$PROJECT_ROOT_PATH/services"
    kontemplate template "${ENVIRONMENT_NAME}-cluster.yaml" --include=$1
  )
fi


