#!/usr/bin/env bash

set -e

IMAGE=$1
VERSION=$2
if kproject container security enabled
then
  kproject container security docker-login
  (
    . "$PROJECT_ROOT_PATH/.tenable-container-registry"
    docker tag "$DOCKER_REPO/$IMAGE:$VERSION" "$TENABLE_IO_DOCKER_REPO/$IMAGE:latest"
    docker tag "$DOCKER_REPO/$IMAGE:$VERSION" "$TENABLE_IO_DOCKER_REPO/$IMAGE:$VERSION"
    docker push "$TENABLE_IO_DOCKER_REPO/$IMAGE:latest"
    docker push "$TENABLE_IO_DOCKER_REPO/$IMAGE:$VERSION"
  )

  info "Pushed $TENABLE_IO_DOCKER_REPO/$IMAGE:$VERSION"

  kproject container security status "$IMAGE" "$VERSION"

fi

