#!/usr/bin/env bash

CONFIG_NAME="$1"

if ! gcloud config configurations describe "$CONFIG_NAME" >/dev/null 2>&1
then
	gcloud config configurations create "$CONFIG_NAME" --no-activate
fi

gcloud config configurations activate "$CONFIG_NAME"

kproject gcloud auth

