#!/usr/bin/env bash

__secret_check_changed() {
  local SECRET_PATH="$1"
  local SECRET_NAME=$(basename "$SECRET_PATH")
  SECRET_NAME=${SECRET_NAME%.gpg}
  SECRET_NAME=${SECRET_NAME%.properties}
  local LOCAL_TS=$(stat -c'%Y' "$SECRET_PATH")
  local REMOTE_TS=$(date -d "$(kubectl get secret "$SECRET_NAME" -o custom-columns=date:metadata.creationTimestamp --no-headers 2>/dev/null)" +'%s')
  if [ "$LOCAL_TS" -gt "$REMOTE_TS" ]
  then
    echo "$SECRET_PATH"
  fi
}

if test -z "$@" || grep -qF ' --all' "$@"
then
  for SECRET_PATH in "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME"/*.gpg
  do
    __secret_check_changed "$SECRET_PATH"
  done
else
  for SECRET_PATH in "$@"
  do
    __secret_check_changed "$SECRET_PATH"
  done
fi

