#!/usr/bin/env bash

set -eo pipefail

__secret_check_changed() {
  local SECRET_PATH="$1"
  local SECRET_NAME=$(basename "$SECRET_PATH")
  SECRET_NAME=${SECRET_NAME%.gpg}
  SECRET_NAME=${SECRET_NAME%.properties}
  local LOCAL_TS
  local REMOTE_TS
  if [ "$(uname)" == "Darwin" ]
  then
    STAT="stat -f%m"
    LOCAL_TS=$($STAT "$SECRET_PATH")
    DATE="date -j -f '%Y%m%d%H%M%S'"
    set +e
    KTIME=$(kubectl get secret "$SECRET_NAME" -o custom-columns=date:metadata.creationTimestamp --no-headers 2>/dev/null | tr -d 'TZ:-')
    set -e
    if [ -z "$KTIME" ]
    then
      REMOTE_TS="0"
    else
      REMOTE_TS=$(date -j -f '%Y%m%d%H%M%S' "$KTIME" +'%s')
    fi
  else
    STAT="stat -c%Y"
    LOCAL_TS=$($STAT "$SECRET_PATH")
    set +e
    REMOTE_TS=$(date -d "$(kubectl get secret "$SECRET_NAME" -o custom-columns=date:metadata.creationTimestamp --no-headers 2>/dev/null)" +'%s')
    set -e
  fi
  if [ "$LOCAL_TS" -gt "$REMOTE_TS" ]
  then
    echo "$SECRET_PATH"
  fi
}

if test -z "$@" || grep -qF ' --all' "$@"
then
  for SECRET_PATH in "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME"/*.gpg
  do
    __secret_check_changed "$SECRET_PATH"
  done
else
  for SECRET_PATH in "$@"
  do
    __secret_check_changed "$SECRET_PATH"
  done
fi

