#!/usr/bin/env bash

export GPG="gpg --use-agent -q --batch" # workaround blackbox_diff not using --use-agent

command cd "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME"

changes=$(blackbox_diff 2>&1 | grep blackbox_edit_end)

if [ -n "$changes" ]
then
  echo
  sed 's/^.*blackbox_edit_end /Will update: /g' <<<"$changes"
  echo
  echo -n "Really re-encrypt [yn]? "
  read yn
  if [ "$yn" == "y" ]
  then
    bash <<<"$changes"
  fi
else
  echo "Nothing to do"
fi

