#!/usr/bin/env bash

skip_confirm="1"

info "Getting ready to sync your remote repository at gs://$CHART_REPO_GCS_BUCKET to local directory ($CHART_REPO_LOCAL_PATH)"

if [ "$skip_confirm" == "1" ]
then
  gsutil -m rsync "gs://$CHART_REPO_GCS_BUCKET" "$CHART_REPO_LOCAL_PATH"
else
  # dry run of the command
  gsutil -m rsync -n "gs://$CHART_REPO_GCS_BUCKET" "$CHART_REPO_LOCAL_PATH"

  read -p "Are you sure you would like to continue with these changes? [y/N]} " confirm
  if [[ $confirm =~ [yY](es)* ]]; then
    gsutil -m rsync "gs://$CHART_REPO_GCS_BUCKET" "$CHART_REPO_LOCAL_PATH"
  else
    error "Discontinuing sync process."
    return 1
  fi
fi

info "Your local directory at $CHART_REPO_LOCAL_PATH now matches the remote chart repository"


