#!/usr/bin/env bash


if grep -q '\--all' <<<"$@"
then
  push_all="1"
  sync_args=" -y"
else
  push_all=""

  sync_args=" -y"
  while getopts ":a" opt; do
    case ${opt} in
      a )
        push_all="1"
        ;;
      \? )
        error_exit "Invalid option $OPTARG"
        ;;
      : )
        error_exit "Invalid option - $OPTARG requires an argument"
        ;;
    esac
  done
  shift $((OPTIND -1))

fi

CHARTS="$@"

if [ "$push_all" == "1" ]
then
  command cd $PROJECT_ROOT_PATH
  CHARTS=$(find services/ -mindepth 2 -maxdepth 2 -type f -name 'Chart.yaml' | xargs dirname)
fi

for CHART in $CHARTS
do
  CHART=$(kproject chart path "$CHART")

  if [ ! -d "$CHART" ]
  then
    error_exit "$CHART not found"
  fi

  info "Building chart $(basename "$CHART")"
  helm package "$CHART" -d "$CHART_REPO_LOCAL_PATH"
done

kproject chart sync pull
info 'Building helm repo index'
helm repo index "$CHART_REPO_LOCAL_PATH" --url "https://$CHART_REPO_GCS_BUCKET.storage.googleapis.com"
kproject chart sync push $sync_args
kproject chart sync pull
info 'Updating helm cache'
helm repo update

