#!/usr/bin/env bash

set -eo pipefail

skip_confirm="0"

while getopts ":y" opt; do
  case ${opt} in
    y )
      skip_confirm="1"
      ;;
    \? )
      error_exit "Invalid option $OPTARG"
      ;;
    : )
      error_exit "Invalid option - $OPTARG requires an argument"
      ;;
  esac
done
shift $((OPTIND -1))

info "Getting ready to sync your local directory ($CHART_REPO_LOCAL_PATH) to a remote repository at gs://$CHART_REPO_GCS_BUCKET"

if [ "$skip_confirm" == "1" ]
then
  gsutil -m rsync "$CHART_REPO_LOCAL_PATH" "gs://$CHART_REPO_GCS_BUCKET"
else
  # dry run of the command
  gsutil -m rsync -n "$CHART_REPO_LOCAL_PATH" "gs://$CHART_REPO_GCS_BUCKET"

  read -p "Are you sure you would like to continue with these changes? [y/N]} " confirm
  if [[ $confirm =~ [yY](es)* ]]; then
    gsutil -m rsync "$CHART_REPO_LOCAL_PATH" "gs://$CHART_REPO_GCS_BUCKET"
  else
    error "Discontinuing sync process."
    return 1
  fi
fi

info "Your remote chart repository now matches the contents of the $CHART_REPO_LOCAL_PATH directory"


