#!/usr/bin/env bash

set -eo pipefail

for CHART in $@
do
  if grep -q / <<<"$CHART"
  then
    CHART="$(command cd "$(dirname "$CHART")"; pwd)/$(basename "$CHART")"
  elif test -d "$CHART"
  then
    CHART="$(command cd "$CHART"; pwd)"
  else
    CHART="$(command cd "$PROJECT_ROOT_PATH/services/$CHART"; pwd)"
  fi
  echo "$CHART"
done

